### ISSUE TITLE
Add to RethinkDB list of client drivers

### ISSUE THREAD

**Issue by Scorpiion** [billysometimes/rethinkdb#12]
There is a list of client drivers for RethinkDB, only the old Dart driver is listed, not this one. I think this driver should be listed as a current community-supported driver, what do you guys think?

http://rethinkdb.com/docs/install-drivers/

**Comment by billysometimes** [comment]
Sure, we can do that! 

I can reach out to somebody on that team today.

**Comment by Scorpiion** [comment]
:+1:

**Comment by billysometimes** [comment]
ok, a ticket is now in rethinkdb's docs for this:
https://github.com/rethinkdb/docs/issues/754
