### ISSUE TITLE
Let Cursor implement Stream

### ISSUE THREAD

**Issue by cgarciae** [billysometimes/rethinkdb#17]
According to the docs

> Streams are lists like arrays, but they’re loaded in a lazy fashion. Operations that return streams return a cursor.

they they tell you
> JavaScript has no native iterator, but ReQL implements an each command similar to jQuery’s.

And your implementation a abides perfectly. But Dart is not JavaScript, we **DO** have streams so why not implement cursor as such? Instead it implements `IterableBase` (which seems resonable) but whenever I put it in a for loop like this
```dart
Cursor users = await r.table('usuarios').run(conn);

  for (Response user in users)
  {
    //What can I do with Response???
  }
```
I get a `Response` object that is useless (no exposed fields or methods). I take that methods like `map`, `where`, etc will also receive this type.

With Dart `1.9.1` and an implementing cursor as a `Stream<Map>` (for example), using `async/await` we could do things like

```dart
var users = await r.table('usuarios').run(conn);
await for (Map user in users)
{
  //Do something as each user is retrieved async 
}
```
or even more sophisticated stuff using `async *`.

**Comment by billysometimes** [comment]
I actually really like this idea, it is the dart way to do things and would *really* simplify the cursor class. 

for example, instead of the toArray() method they toList() method is built right into streams, and really every other cursor method as well.

**Comment by billysometimes** [comment]
https://github.com/billysometimes/rethinkdb/tree/cursor-stream/
