### ISSUE TITLE
2.1 Support

### ISSUE THREAD

**Issue by FaisalAbid** [billysometimes/rethinkdb#26]
Do we need to do any work to support the new failover stuff?
http://rethinkdb.com/blog/2.1-release/

**Comment by billysometimes** [comment]
Work will need to be done for SSL(https://github.com/rethinkdb/rethinkdb/pull/4080) and the Math(https://github.com/rethinkdb/rethinkdb/issues/866) commands, but failover shouldn't depend on driver updates. I'll break those out into separate tickets.

**Comment by FaisalAbid** [comment]
lol it looks like when i made some changes before, I added the math commands before the release. So just SSL.

Also i think we might have to do something with these new error stuff?

https://groups.google.com/forum/#!topic/rethinkdb-dev/6GeJW-srWAg

**Comment by billysometimes** [comment]
Well that is good news.  Yeah the new typed errors will certainly be a big new feature for the driver.  I'll add a ticket for that as well.
