### ISSUE TITLE
Async/Await support

### ISSUE THREAD

**Issue by FaisalAbid** [billysometimes/rethinkdb#3]
It would be pretty cool to have async/await support for this library. 

What do you think is the best way to approach this? It seems like a pretty big refactor unless I'm wrong.

**Comment by billysometimes** [comment]
Added.  You can now do something like this:

main() async{
  Rethinkdb r = new Rethinkdb();
  var ourConnection = await r.connect(db: "test",port: 28015);
  print(await r.dbList().run(ourConnection));
}

**Comment by FaisalAbid** [comment]
@billysometimes  Ah! thats pretty neat. I will check it out for sure

**Comment by FaisalAbid** [comment]
Closing this issue for now!
