### ISSUE TITLE
Errors produced by correct query

### ISSUE THREAD

**Issue by fschuetz04** [billysometimes/rethinkdb#31]
Given the following document in `teams` table
```json
{
  "id": "teamId",
  "members": {
    "userId1": true,
    "userId2": true
   }
}
```
the following query works fine in RethinkDB Administration Console
```js
r.db('test')
 .table('teams')
 .filter(r.row('members')
 .hasFields('userId1'))
 .concatMap(r.row('members').keys())
 .distinct()
 .eqJoin(r.row, r.db('test').table('users'))
 .zip();
```
and returns the user documents for `userId1` and `userId2`.
But the same query produces errors for the .filter() and .eqJoin() part with this driver. (for sure with an added `run(connection)` statement)

Does anybody know why?

**Comment by billysometimes** [comment]
Thanks for filing the bug! 

eqJoin should've been scanning for implicitVars such as r.row but was not. A fix has been committed, but not pushed to pub.  A workaround until a new version of the driver is released is to use an anonymous function instead of r.row for eqJoin:
```dart
r.db('test')
...
.eqJoin((row)=>row,r.db('test').table('users'))
...
```
or you can pull the latest code from github.

**Comment by fschuetz04** [comment]
Thanks for the fast reply!

I'll try it with the latest code from github.

**Comment by fschuetz04** [comment]
Okay, `eqJoin()` works fine with the latest code, but `filter(r.row.hasFields('userId1'))` still fails:
```
Converting object to an encodable object failed.
```
Simple queries like `filter({'id': 'teamId'})` work, but something with `r` used unfortunately not.

**Comment by billysometimes** [comment]
are you doing 
```dart
r.row.hasFields('userId1')
```
or
```dart
r.row('members').hasFields('userId1')
```
because the second works, I do not believe the first is a valid rql statement in the JS drivers either.

**Comment by fschuetz04** [comment]
Currently, I'm doing the first one, but I'll try out the second one.
According to the documentation, the first should be valid - see the third example at http://rethinkdb.com/api/javascript/row/. (and it works in RethinkDB Administration Console)

**Comment by billysometimes** [comment]
Ah thank you, you are correct that it is indeed valid, but it also appears to be working for the dart driver as well.  It is just returning an empty array because r.row has no field named 'userId1'.

I am not getting the error
```dart
Converting object to an encodable object failed.
```

would you mind posting the exact query? 

```dart
r.db('test')
 .table('teams')
 .filter(r.row)  //returns all records

r.db('test')
 .table('teams')
 .filter(r.row.hasFields('userId1')  //returns an empty array

r.db('test')
 .table('teams')
 .filter(r.row.hasFields('members')  //returns any record with the field "members"

r.db('test')
 .table('teams')
 .filter(r.row('members').hasFields('userId1')  //returns any record where the 'members' field has 
a field   named 'userId1'

**Comment by fschuetz04** [comment]
The exact query I use is:
```dart
r.table('teams')('members')
  .filter(r.row.hasFields(userId))
  .concatMap(r.row.keys()).distinct()
  .eqJoin(r.row, r.table('users')).zip()
  .run(rConnection);
```
I realized I can just use `.filter(r.row(userId))` instead of `.filter(r.row.hasFields(userId))`, but this doesn't work as well.

**Comment by billysometimes** [comment]
Your query is working for me. what does your `user` table look like, because I only added sample data like this:
```dart
[
  {
    "id":"userId1",
    "name":"Baz"
  },
  {
    "id":"userId2",
    "name":"Gak"
  },
]
```
using your query above I get the return value of:
```dart
  [{id: userId1, name: Baz}, {id: userId2, name: Gak}]
```

**Comment by fschuetz04** [comment]
Also just using sample data:
```js
[
  {
    'email': 'hedda.conner@example.com',
    'fullName': 'Hedda Conner',
    'id': 'd429f4f3-edd0-41a5-a981-39e5db507760',
    'passwordHash': '$2a$10$jh/26THyaO6.CT6qODLm4.qj/a2z3tmXOCDb3l9/eLu/LlIYPWkRC',
    'username': 'hconner'
  },
  {
    'email': 'russell.moreno@example.com',
    'fullName': 'Russell Moreno',
    'id': '5cff7d1c-e0c1-4d45-84d3-1001ef08af0d',
    'passwordHash': '$2a$10$ps/mOdRmpF02G9Dyu/OCv.Xdf.4OTpJZeL1FMCr5GFFJ7tsL7cxOO',
    'username': 'rmoreno'
  }
]
```
So there should be no difference ... I'll try to test it out with another test database simplier data.

**Comment by fschuetz04** [comment]
Just saw that you pushed to the repo and I didn't pull yet - that makes probably the difference ...

**Comment by billysometimes** [comment]
Ha, that might make a difference.
Also if your issue is still 
```
Converting object to an encodable object failed.
```

That appears to be a `dart:convert` JSON error, not a rethinkdb error. If you are trying to convert a dart object to json, you'll have to give it a `toJson()` method that returns a map.

**Comment by fschuetz04** [comment]
I'm not importing dart:convert, so this must have to do something with this library. I'll test it out tomorrow.

**Comment by fschuetz04** [comment]
Strange thing: Using the complex data for the `users` table, `res` in `Query.serialize()` (https://github.com/billysometimes/rethinkdb/blob/master/lib/src/net.dart#L26) is only
```
[1, [16, [[15, [users]], bc783dd4-1f57-4b41-ba0a-8266c1081c8a]], {db: [14, [test]]}]
```
producing the `Converting object to an encodable object failed.` error. When I use the simple data, `res` looks like
```
[1, [72, [[50, [[42, [[40, [[39, [[31, [[15, [teams]], members]], [69, [[2, [0]], [31, [[13, []], userId1]]]]]], [69, [[2, [1]], [94, [[13, []]]]]]]]]], [69, [[2, [2]], [13, []]]], [15, [users]]]]]], {db: [14, [test]]}]
```
and everything works fine.

**Comment by fschuetz04** [comment]
Okay, sorry for the trouble. Just forgot an await keyword so there was a uncompleted future in `res` :rage:

**Comment by FaisalAbid** [comment]
Happens to the best of us! Glad it worked out
