### ISSUE TITLE
.map() function

### ISSUE THREAD

**Issue by fschuetz04** [billysometimes/rethinkdb#34]
I don't get how the `.map()` function actually works.

If I write something like:
```dart
Cursor teams = await r.table('teams').filter(r.row('members').hasFields(userId))
  .map((team) => team.merge({
    'members': team('members')
      .coerceTo('array')
      .map((member) => r.object(['userId', member(0)))
  });
```

With the teams table looking like:
```json
{
  "id": "e5ab2282-1fc4-4b9a-8bd0-d081340de477" ,
  "members": {
    "5cff7d1c-e0c1-4d45-84d3-1001ef08af0d": {
      "role": "member"
    } ,
    "69481503-7bbc-40e6-bb4a-cde1bc98504b": {
      "role": "member"
    } ,
    "6c753ce2-65bc-4904-85b9-e16bc9626d5e": {
      "role": "owner"
    } ,
    "85257fce-9bd7-4b31-9d50-ca2f626a04e5": {
      "role": "member"
    } ,
    "bc697d45-2c5f-4b51-ac04-7a6e84424840": {
      "role": "member"
    } ,
    "dcb08ae1-0032-4091-996d-3e6b78d410c3": {
      "role": "member"
    }
  } ,
  "name": "Team Mccarthy"
}
```

The inner `.map()` function fails with the following: `Cannot perform get_field on a non-object non-sequence "5cff7d1c-e0c1-4d45-84d3-1001ef08af0d".`

**Comment by billysometimes** [comment]
I'm not getting that error, however I am getting errors because of an extra open bracket and a missing end parenthesis:
```dart
  r.table('teams').filter(r.row('members').hasFields(userId))
  .map((team) => team.merge({
    'members': team('members')
    .coerceTo('array')
    //line previously had r.object([
    .map((member) => r.object('userId', member(0)))
    //line previously had }) 
  }))
```

once those changes are made, I get a cursor containing the result:
{
  id: e5ab2282-1fc4-4b9a-8bd0-d081340de477, 
  members: [
    {userId: 5cff7d1c-e0c1-4d45-84d3-1001ef08af0d}, 
    {userId: 69481503-7bbc-40e6-bb4a-cde1bc98504b}, 
    {userId: 6c753ce2-65bc-4904-85b9-e16bc9626d5e}, 
    {userId: 85257fce-9bd7-4b31-9d50-ca2f626a04e5}, 
    {userId: bc697d45-2c5f-4b51-ac04-7a6e84424840},
     {userId: dcb08ae1-0032-4091-996d-3e6b78d410c3}
  ],
  name: Team Mccarthy
}

**Comment by fschuetz04** [comment]
No it doesn't help unfortanetly.

This is my complete code:
```dart
import 'package:rethinkdb_driver/rethinkdb_driver.dart';

main() async {
  try {
    var r = new Rethinkdb(), connection = await r.connect(db: '2gathr');

    var userId = '5cff7d1c-e0c1-4d45-84d3-1001ef08af0d';
    var teams = await r.table('teams')
      .map((team) => team.merge({
        'members': team('members')
          .coerceTo('array')
          .map((member) => r.object('userId', member(0)))
      }))
      .run(connection);

    print(await teams.toList());
  } catch (e) {
    print(e.message);
  }
}
```

And it always prints this error message ...

**Comment by billysometimes** [comment]
Ah, I think I have found the issue.

the get_field term was renamed to bracket. I had been using the 2.1 branch to test your code, which had the appropriate change.  This change had not been made in the master branch.

The term change has been made in master now.

**Comment by fschuetz04** [comment]
Thank you :)
