### ISSUE TITLE
DateTime support

### ISSUE THREAD

**Issue by fschuetz04** [billysometimes/rethinkdb#35]
When I try something like
```dart
await r.table('sessions').insert({'issuedAt': new DateTime.now()}).run(connection);
```
it throws a RqlRuntimeError with the message `Timezone 1 does not start with - or +.` Should I use timestamps instead?

**Comment by billysometimes** [comment]
Thanks for filing the bug!

It looks like there is a bug if the timeline is ahead of gmt. I'll fix it today or tomorrow, in the meantime you could use r.epochtime and pass it a timestamp

**Comment by fschuetz04** [comment]
Ok thanks I'll try that :+1:
