### ISSUE TITLE
.delete() with returnChanges

### ISSUE THREAD

**Issue by fschuetz04** [billysometimes/rethinkdb#37]
Whenever I try to set the `returnChanges` option to `true` for the `.delete()` statement, a RqlCompileError is thrown: `Unrecognized optional argument returnChanges.`

My code looks like this:
```dart
Map response = await r.table('sessions').delete({'returnChanges': true}).run(connection);
```

**Comment by billysometimes** [comment]
Yeah, the dart driver uses underscores like the python driver. Try
return_changes
