### ISSUE TITLE
Verify parallel execution of queries on a single connection works

### ISSUE THREAD

**Issue by billysometimes** [billysometimes/rethinkdb#6]

**Comment by FaisalAbid** [comment]
What do you think the best way to verify this is?

**Comment by billysometimes** [comment]
I added this based on https://github.com/rethinkdb/rethinkdb/issues/3754

I added a test directory with a unit test that addresses item 2 in the issue, however I haven't found a good way to test 1 or 3. But since it is really a server change and not a driver change, it really shouldn't affect us.
