### ISSUE TITLE
.count() not working to lists

### ISSUE THREAD

**Issue by idrats** [billysometimes/rethinkdb#61]
Even `r.expr([1,2,3]).count()` will return `0` instead of `3`.
Also queries like `r.db('db').table('table').filter(r.row('listField').count().eq(3))` are working perfect at admin web interface. But not working at dart code.

**Comment by billysometimes** [comment]
Thanks for reporting, I've published a new version of the rethinkdb_driver package that fixes this, `2.3.2+2`

In the future I'd like to re-organize the code so that the constructor doesn't have to do so much null checking.
