### ISSUE TITLE
Any news on upgrading to Dart 3?

### ISSUE THREAD

**Issue by black-purple** [billysometimes/rethinkdb#70]
I hope the contributors are planing to update to dart 3, I really need to use this package in a project

**Comment by billysometimes** [comment]
There's not going to be any more development on the repo, please use @marceloneppel's driver https://github.com/marceloneppel/rethinkdb

According to pub his driver is dart 3 compatible https://pub.dev/packages/rethink_db_ns

**Comment by black-purple** [comment]
Thank you for your response, I will check it outright away!
